# Generated by Django 2.2 on 2019-05-09 18:58

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafana',
            name='chart',
            field=models.CharField(choices=[('', '[ -- 데이터를 선택하세요 -- ]'), ('Kmong', (('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426876991&to=1557427776991&theme=light&panelId=6', '분당 전환율'), ('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426920716&to=1557427820716&theme=light&panelId=4', '페이지별 조회 수'), ('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426958731&to=1557427858731&theme=light&panelId=2', '사용기기별 접근 수'))), ('NC_Soft', (('21', 'Books'), ('22', 'Games'))), ('Zigzag', (('31', 'Groceries'), ('32', 'Restaurants')))], default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grafana',
            name='end_time',
            field=models.DateTimeField(default=home.models.now_plus_15min),
        ),
        migrations.AlterField(
            model_name='grafana',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
