# Generated by Django 2.2 on 2019-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190510_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafana',
            name='chart',
            field=models.CharField(choices=[('', '[ -- 데이터를 선택하세요 -- ]'), ('Kmong', (('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426876991&to=1557427776991&theme=light&panelId=6', '분당 전환율'), ('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426920716&to=1557427820716&theme=light&panelId=4', '페이지별 조회 수'), ('http://class14.encore.com:23000/d-solo/rgUwEJmZk/kmong-dashboard?orgId=1&from=1557426958731&to=1557427858731&theme=light&panelId=2', '사용기기별 접근 수'))), ('NC_Soft', (('21', 'Books'), ('22', 'Games'))), ('Zigzag', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=500),
        ),
    ]
